# Generated by Django 4.2.2 on 2023-06-18 01:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
